# Generated by Django 5.0.6 on 2024-06-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_rename_imagen_persona_foto_remove_persona_fecha_ncto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mancuerna',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mancuerna',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mancuerna',
            name='peso',
            field=models.IntegerField(choices=[(10, '10 kg'), (20, '20 kg')], default=10),
        ),
        migrations.AlterField(
            model_name='mancuerna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mancuerna',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.persona'),
        ),
    ]
