# Generated by Django 5.0.6 on 2024-06-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_carrito_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
