# Generated by Django 5.0.6 on 2024-06-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_remove_perfil_usuario_delete_carrito_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancuerna',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
