# Generated by Django 5.0.6 on 2024-06-29 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_alter_mancuerna_peso_alter_mancuerna_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancuerna',
            name='peso',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
