# Generated by Django 5.0.6 on 2024-06-30 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_alter_mancuerna_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancuerna',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
