# Generated by Django 5.0.6 on 2024-07-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_alter_mancuerna_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancuerna',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
