# Generated by Django 5.0.6 on 2024-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_carritoitem_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancuerna',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
