# Generated by Django 5.0.6 on 2024-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_remove_mancuerna_propietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(default='Calle Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default='Comuna Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dpto_casa_oficina',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(default='Región Desconocida', max_length=100),
        ),
    ]
